spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://0000.0000.0000.0000:00000/0000
    username: 0000
    password: 000000
  #   Redis 配置
  redis:
    database: 1
    host: 0000.0000.0000.0000
    port: 000000
    timeout: 5000
    password: 000000
