spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: carspacesdemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://0000.0000.0000.0000:00000/0000
    username: 0000
    password: 000000
  #   Redis 配置
  redis:
    database: 1
    host: 0000.0000.0000.0000
    port: 000000
    timeout: 5000
    password: 000000
server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

yuapi:
  client:
    access-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
